[package]
name = "robotica-node-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
paho-mqtt = "0.11.1"
tokio = { version = "1.19.2", features = ["full"] }
serde = { version= "1.0.139", features = ["derive"] }
serde_json = "1.0.82"
anyhow = "1.0.58"
reqwest = "0.11.11"
serde_path_to_error = "0.1.7"
gethostname = "0.2.3"

[workspace]
members = ["brian-node-rust"]